### ISSUE TITLE
Bug: When body of document has some big value, scrolling page separates the bottom part of menu

### ISSUE THREAD

**Issue by tomek2864** [ruvkr/react-components-by-ruvkr#1]
### 🐛 Bug

When I set height of document on some higher value like 5000px, and after that I'm scrolling the page the bottom bar of menu is moving.

![2020-12-10_19h35_48](https://user-images.githubusercontent.com/41157091/101814846-f88d4e80-3b1e-11eb-9c09-c997a660e6b3.gif)

**Comment by ruvkr** [comment]
Thank you for the bug report. 
Please check my latest commit. I fixed the scrolling issue.

**Comment by tomek2864** [comment]
It works. Thank you
