### ISSUE TITLE
BUG: Burger bar click Expands and collapses quickly.

### ISSUE THREAD

**Issue by jafin** [ruvkr/react-components-by-ruvkr#2]
When I tried the project demo in Chrome v88 (Windows) I noticed this behaviour when clicking on the 'burger bars?' 
![MDcnIVenTg](https://user-images.githubusercontent.com/127927/106975778-e0dee900-67a2-11eb-9983-e910f10325ab.gif)

**Comment by ruvkr** [comment]
Thanks for the report. I'm looking into it. Will update soon.

**Comment by ruvkr** [comment]
Hey, I Updated SideDrawer component. Can you please test again?

**Comment by jafin** [comment]
@ruvkr - Yep looks good on my machine!.    The original issue is not visible.   Using the demo now an odd behaviour is every click on the 'burger bars' doesn't register, so if I click it 4 times it may trigger  the panel to open maybe 1 in 4 goes.  Not sure why.

**Comment by ruvkr** [comment]
That should not happen. Can you open an incognito tab and try. Maybe some extensions causing the issue?
Also, are you on Windows 10?

**Comment by jafin** [comment]
@ruvkr 
I tried in cognito, no extensions loaded. Can reproduce.  In video I can clicking probably once a second, as seen it doesn't open. Dragging the panel out works fine.
This is in chrome 88.0.4324.150 Windows 10.
I also tried Canary chrome 90.0.4411.0 (Official Build) canary (64-bit).  Which showed similar result
I tried Firefox, no issue works perfect.
In Edge Version 88.0.705.63 (Official build) (64-bit), similar issue to chrome.


![YMz6h0zaxW](https://user-images.githubusercontent.com/127927/107351337-35bd8f00-6b16-11eb-89b0-67b41b8869ac.gif)

I hope that helps.

**Comment by ruvkr** [comment]
Hey, I tried this on VM running Windows 10 and found no issue, but asked a friend to try and he faces this clicking issue on his Windows 10 machine. I will go to his place and try to debug there in a couple of days.

https://user-images.githubusercontent.com/34903858/107521174-3dde0300-6bd8-11eb-92af-08da7ee3aa17.mp4

**Comment by ruvkr** [comment]
Hey, I updated the burger button, Can you please test again.

**Comment by jafin** [comment]
@ruvkr 100% working!! :100:
