### ISSUE TITLE
BUG: Firefox drag out side menu and it stays out broken.

### ISSUE THREAD

**Issue by rluiten** [ruvkr/react-components-by-ruvkr#3]
Your controls look nice and useful.

I was playing with demo and noticed this.
It does not snap out or snap back like it does in Chrome if you drag it out manually but not all the way.
Attached a demo gif.

![firefox-drag-out-side-menu](https://user-images.githubusercontent.com/670472/107030455-693da800-67fc-11eb-9df5-4b95744ff23c.gif)

**Comment by ruvkr** [comment]
Thanks for the report. Looking into it now.

**Comment by ruvkr** [comment]
Can you tell me the version of FF and os. Is it always happening?

**Comment by rluiten** [comment]
I was at work initially and it is Firefox 85, but also happens at home with FF 84.05 as i just tested.
Yes its 100% reproducible just drag out the side men 50 - 80% and let it go.

**Comment by rluiten** [comment]
Oops forgot to state OS.
I am on Windows 10 at home FF84.05 and work FF85.

**Comment by ruvkr** [comment]
Hey, I Updated SideDrawer component. Can you please test again?

**Comment by rluiten** [comment]
Looks like its fixed, could not reproduce the behavior even once in 20 attempts and a few reloads.

**Comment by ruvkr** [comment]
That's good to hear. Can you close it now?
